name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # - name: Set bot token
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     command: dokku config:set --no-restart fumode BOT_TOKEN=${{ secrets.BOT_TOKEN }}
      #     host: "162.243.164.100"
      #     username: root
      #     privateKey: ${{ secrets.PRIVATE_KEY}}
      - name: Dokku deploy
        uses: vitalyliber/dokku-github-action@v3.0
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          HOST: "162.243.164.100"
          PROJECT: fumomap
